#!/bin/bash
# Generate large-scale test manifests for scalability testing
# Creates .skill-engine.toml files with 10, 50, and 100 skills

set -e

# Colors
GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'

generate_manifest() {
    local num_skills=$1
    local output_file=$2
    local tools_per_skill=${3:-3}

    echo -e "${CYAN}Generating manifest with $num_skills skills...${NC}"

    # Start manifest
    cat > "$output_file" << 'EOF'
# Large-scale test manifest for performance testing
# Generated by generate-large-manifest.sh

EOF

    # Generate skills
    for i in $(seq 1 $num_skills); do
        # Pad skill number to 3 digits for sorting
        skill_num=$(printf "%03d" $i)

        cat >> "$output_file" << EOF
[skills.skill-$skill_num]
source = "./skill-$skill_num"
runtime = "wasm"
description = "Test skill number $i for scalability testing with multiple tools and parameters"
version = "1.0.0"
category = "testing"
tags = ["test", "performance", "scale"]

EOF

        # Generate tools for this skill
        for j in $(seq 1 $tools_per_skill); do
            cat >> "$output_file" << EOF
[[skills.skill-$skill_num.tool]]
name = "tool-$j"
description = "Tool number $j for skill-$skill_num - performs test operation $j"
command = "echo 'Executing tool $j for skill $skill_num'"

[[skills.skill-$skill_num.tool.parameter]]
name = "input"
type = "string"
description = "Input parameter for tool $j"
required = true

[[skills.skill-$skill_num.tool.parameter]]
name = "output"
type = "string"
description = "Output parameter for tool $j"
required = false
default = "stdout"

EOF
        done

        echo "" >> "$output_file"
    done

    echo -e "${GREEN}✓ Created $output_file with $num_skills skills ($tools_per_skill tools each)${NC}"

    # Show file size
    local size=$(wc -c < "$output_file" | tr -d ' ')
    local size_kb=$((size / 1024))
    echo "  File size: ${size_kb}KB"

    # Count lines
    local lines=$(wc -l < "$output_file" | tr -d ' ')
    echo "  Lines: $lines"
    echo ""
}

echo ""
echo "========================================"
echo "  Large Manifest Generator"
echo "========================================"
echo ""

# Generate different sized manifests
generate_manifest 10 "/tmp/large-manifest-10.toml" 3
generate_manifest 50 "/tmp/large-manifest-50.toml" 3
generate_manifest 100 "/tmp/large-manifest-100.toml" 2

echo "========================================"
echo "  Summary"
echo "========================================"
echo ""
echo "Generated manifests in /tmp/:"
echo "  - large-manifest-10.toml   (10 skills, 3 tools each)"
echo "  - large-manifest-50.toml   (50 skills, 3 tools each)"
echo "  - large-manifest-100.toml  (100 skills, 2 tools each)"
echo ""
echo "Use with: skill claude generate --manifest /tmp/large-manifest-50.toml"
echo ""
